### ISSUE TITLE
通讯录联系人排序有误

### ISSUE THREAD

**Issue by manbu109910915** [netease-im/NIM_iOS_SDK#3]
运行了网易云信的demo，将通讯录中的一名联系人备注改为“沈阳”，通讯录中没有出现在S组，而是出现在了C组中。

**Comment by emilyzyw** [comment]
谢谢反馈，这边会修正

**Comment by emilyzyw** [comment]
这个问题是因为 沈 是多音字 =。= 也读作 [chén]
